#!/usr/bin/env bash
source functions.sh
set -e

echo "IriusRisk On-Premise Interactive Setup Wizard"
echo "--------------------------------------------"

# —————————————————————————————————————————————————————————————
# 0. Decide which container engine to use (passed-in or standalone)
# —————————————————————————————————————————————————————————————
prompt_engine

# —————————————————————————————————————————————————————————————
# 1. Set override & SAML-file paths once, for downstream logic
# —————————————————————————————————————————————————————————————
COMPOSE_FILE="../container-compose/container-compose.yml"
SAML_FILE="../container-compose/container-compose.saml.yml"
NGINX_OVERRIDE="../container-compose/container-compose.nginx.yml"

if [[ "$CONTAINER_ENGINE" == "docker" ]]; then
    OVERRIDE_FILE="../container-compose/container-compose.docker.yml"
elif [[ "$CONTAINER_ENGINE" == "podman" ]]; then
    OVERRIDE_FILE="../container-compose/container-compose.podman.yml"
fi

# —————————————————————————————————————————————————————————————
# 2. Prompt for key values (with validation)
# —————————————————————————————————————————————————————————————
HOST_NAME=$(prompt_nonempty "Enter the public hostname for your IriusRisk instance (HOST_NAME, e.g. iriusrisk.example.com)")

# Internal or external Postgres
if [[ -n "$USE_INTERNAL_PG" ]]; then
    echo "Using internal Postgres setting: $USE_INTERNAL_PG"
else
    USE_INTERNAL_PG=$(prompt_yn "Do you want to use an internal Postgres container")
fi

if [[ "$USE_INTERNAL_PG" == "y" ]]; then
    DB_IP="postgres"
else
    # Use DB_IP from env if set (for local install), otherwise prompt
    if [[ -n "$DB_IP" ]]; then
        echo "Using Postgres IP address from environment: $DB_IP"
    else
        DB_IP=$(prompt_nonempty "Enter the Postgres IP address (DB host)")
    fi
fi

# Use DB_PASS from env if set (for local install), otherwise prompt
if [[ -n "$DB_PASS" ]]; then
    echo "Using Postgres password from environment."
else
    DB_PASS=$(prompt_nonempty "Enter the Postgres password")
fi

# Properly escape JDBC URL for YAML
JDBC_URL="jdbc\\:postgresql\\://$DB_IP\\:5432/iriusprod?user\\=iriusprod&password\\=$DB_PASS"

# Properly escape protocol colon in IRIUS_EXT_URL
IRIUS_EXT_URL="https\\\\://$HOST_NAME"

# —————————————————————————————————————————————————————————————
# 3. Build JDBC_URL, and create secret if using podman
# —————————————————————————————————————————————————————————————

if [[ "$CONTAINER_ENGINE" == "docker" ]]; then
    # Properly escape JDBC URL for YAML
    JDBC_URL="jdbc\\:postgresql\\://$DB_IP\\:5432/iriusprod?user\\=iriusprod&password\\=$DB_PASS"
elif [[ "$CONTAINER_ENGINE" == "podman" ]]; then
    JDBC_URL="jdbc\\:postgresql\\://$DB_IP\\:5432/iriusprod?user\\=iriusprod"

    # Fixed UID/email
    GPG_EMAIL="db-secrets@iriusrisk.local"

    # If we don't already have that key, generate it in batch mode
    if ! gpg --list-keys "$GPG_EMAIL" >/dev/null 2>&1; then
        cat > /tmp/gpg_batch <<EOF
%no-protection
Key-Type: RSA
Key-Length: 2048
Name-Real: IriusRisk DB Secret Key
Name-Comment: autogenerated for DB encryption
Name-Email: ${GPG_EMAIL}
Expire-Date: 0
EOF

        gpg --batch --generate-key /tmp/gpg_batch
        rm /tmp/gpg_batch
    fi

    # Pull out the *long* fingerprint (UUID) for that key
    GPG_RECIPIENT=$(
      gpg --list-keys --with-colons "$GPG_EMAIL" \
        | awk -F: '/^pub/ { print $5; exit }'
    )

    # Now encrypt DB_IP to db_pwd.gpg
    echo -n "${DB_IP}" \
    | gpg --batch --yes --encrypt \
            --recipient "${GPG_RECIPIENT}" \
            --output db_pwd.gpg

    # Create the Podman secret with the pass driver
    sudo podman secret rm db_pwd 2>/dev/null || true
    sudo podman secret create --driver=pass db_pwd db_pwd.gpg

    # Remove the local .gpg after loading it into Podman
    rm db_pwd.gpg
fi

# —————————————————————————————————————————————————————————————
# 4. SAML setup
# —————————————————————————————————————————————————————————————
if [[ -n "$SAML_CHOICE" ]]; then
    ENABLE_SAML="$SAML_CHOICE"
    echo "SAML setup: Using value from one-click ('${SAML_CHOICE}')"
else
    ENABLE_SAML=$(prompt_yn "Do you want to enable SAML support")
fi

if [[ "$ENABLE_SAML" == "y" ]]; then
    SAML_KEYSTORE_PASSWORD=$(prompt_nonempty "Enter SAML keystore password (KEYSTORE_PASSWORD)")
    SAML_KEY_ALIAS_PASSWORD=$(prompt_nonempty "Enter SAML key alias password (KEY_ALIAS_PASSWORD)")
fi

# —————————————————————————————————————————————————————————————
# 5. Safely update override file & generate certificates
# —————————————————————————————————————————————————————————————

if [[ ! -f "$OVERRIDE_FILE" ]]; then
    echo "ERROR: $OVERRIDE_FILE not found. Please ensure you have cloned the repo and have the override template."
    exit 1
fi

# Update NG_SERVER_NAME (replace any occurrence)
sed -i "s|NG_SERVER_NAME=.*|NG_SERVER_NAME=$HOST_NAME|g" "$OVERRIDE_FILE"
# Update IRIUS_EXT_URL (replace \${HOST_NAME} or any existing value)
sed -i "s|IRIUS_EXT_URL=.*|IRIUS_EXT_URL=$IRIUS_EXT_URL|g" "$OVERRIDE_FILE"
# Remove existing IRIUS_DB_URL line (escaped or not)
sed -i '/IRIUS_DB_URL=/d' "$OVERRIDE_FILE"
# Insert a correct line after 'environment:' under tomcat:
awk -v db_url="      - IRIUS_DB_URL=$JDBC_URL" '
    BEGIN {tomcat=0}
    /tomcat:/ {print; tomcat=1; next}
    tomcat && /environment:/ {
        print
        print db_url
        tomcat=0
        next
    }
    {print}
' "$OVERRIDE_FILE" > "${OVERRIDE_FILE}.tmp" && mv "${OVERRIDE_FILE}.tmp" "$OVERRIDE_FILE"

echo "Updated $OVERRIDE_FILE"

ensure_certificates $HOST_NAME

# —————————————————————————————————————————————————————————————
# 6. Safely update SAML override if enabled
# —————————————————————————————————————————————————————————————
if [[ "$ENABLE_SAML" == "y" ]]; then
    if [[ ! -f "$SAML_FILE" ]]; then
        echo "ERROR: $SAML_FILE not found. Please ensure you have the SAML override template."
        exit 1
    fi
    # Replace or insert KEYSTORE_PASSWORD and KEY_ALIAS_PASSWORD under the tomcat environment:
    if grep -q 'KEYSTORE_PASSWORD=' "$SAML_FILE"; then
        sed -i "s|KEYSTORE_PASSWORD=.*|KEYSTORE_PASSWORD=$SAML_KEYSTORE_PASSWORD|g" "$SAML_FILE"
    else
        # Insert under 'environment:' for tomcat
        awk -v newvar="      - KEYSTORE_PASSWORD=$SAML_KEYSTORE_PASSWORD" '
            BEGIN {in_env=0; in_tomcat=0}
            /tomcat:/ {print; in_tomcat=1; next}
            in_tomcat && /environment:/ {print; print newvar; in_env=1; in_tomcat=0; next}
            {print}
        ' "$SAML_FILE" > "${SAML_FILE}.tmp" && mv "${SAML_FILE}.tmp" "$SAML_FILE"
    fi
    if grep -q 'KEY_ALIAS_PASSWORD=' "$SAML_FILE"; then
        sed -i "s|KEY_ALIAS_PASSWORD=.*|KEY_ALIAS_PASSWORD=$SAML_KEY_ALIAS_PASSWORD|g" "$SAML_FILE"
    else
        awk -v newvar="      - KEY_ALIAS_PASSWORD=$SAML_KEY_ALIAS_PASSWORD" '
            BEGIN {in_env=0; in_tomcat=0}
            /tomcat:/ {print; in_tomcat=1; next}
            in_tomcat && /environment:/ {print; print newvar; in_env=1; in_tomcat=0; next}
            {print}
        ' "$SAML_FILE" > "${SAML_FILE}.tmp" && mv "${SAML_FILE}.tmp" "$SAML_FILE"
    fi
    echo "Updated $SAML_FILE"
else
    echo "Skipping SAML override file as SAML is not enabled."
fi

# —————————————————————————————————————————————————————————————
# 7. Safely update nginx override
# —————————————————————————————————————————————————————————————

if [[ "$CONTAINER_ENGINE" == "docker" ]]; then
  cat > "$NGINX_OVERRIDE" <<EOF
version: '3.7'
services:
  nginx:
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    image: docker.io/continuumsecurity/iriusrisk-prod:nginx
    container_name: iriusrisk-nginx
    networks:
      - iriusrisk-frontend
    mem_reservation: 50M
    mem_limit: 200M
    cpu_shares: 128
    volumes:
      - "./cert.pem:/etc/nginx/ssl/star_iriusrisk_com.crt:ro"
      - "./key.pem:/etc/nginx/ssl/star_iriusrisk_com.key:ro"
EOF

elif [[ "$CONTAINER_ENGINE" == "podman" ]]; then
  cat > "$NGINX_OVERRIDE" <<EOF
version: '3.7'
services:
  nginx:
    ports:
      - "80:80"
      - "443:443"
    image: localhost/nginx-rhel
    container_name: iriusrisk-nginx
    networks:
      - iriusrisk-frontend
    mem_reservation: 50M
    mem_limit: 200M
    volumes:
      - "./cert.pem:/etc/nginx/ssl/star_iriusrisk_com.crt:z"
      - "./key.pem:/etc/nginx/ssl/star_iriusrisk_com.key:z"
EOF

fi


# —————————————————————————————————————————————————————————————
# 8. Safely update main compose file
# —————————————————————————————————————————————————————————————

# For Docker, ensure restart policy exists under each service
if [[ "$CONTAINER_ENGINE" == "docker" ]]; then
    echo "Modifying base file for docker (only in services section)…"
    sed -i '/^services:/,${/^  [A-Za-z0-9_-]\+:[ ]*$/{
N
/\n    restart:/!s/\n/\n    restart: unless-stopped\n/
}}' "$COMPOSE_FILE"
fi

# —————————————————————————————————————————————————————————————
# 9. Summary
# —————————————————————————————————————————————————————————————
echo
echo "--------------------------------------------"
echo "Setup complete. Summary of your values:"
echo "Container engine:      $CONTAINER_ENGINE"
echo "Host name:             $HOST_NAME"
echo "Postgres host/IP:      $DB_IP"
echo "Postgres password:     [set]"
echo "Override file:         $OVERRIDE_FILE"
if [[ "$ENABLE_SAML" == "y" ]]; then
    echo "SAML enabled:          yes"
    echo "KEYSTORE_PASSWORD:     [set]"
    echo "KEY_ALIAS_PASSWORD:    [set]"
    echo "SAML override file:    $SAML_FILE"
else
    echo "SAML enabled:          no"
fi
echo
echo "You can rerun this wizard to update your settings anytime."
