version: '3.7'

services:
  tomcat:
    secrets:
      - db_pwd
      - db_privkey
      - keystore_pwd
      - keystore_privkey
      - key_alias_pwd
      - key_alias_privkey
    environment:
      - CATALINA_OPTS=
            -"Dsaml.config.path=/etc/irius/SAMLv2-config.groovy"
            -XX:+UseParallelGC
            -XX:+UseContainerSupport
            -XX:MetaspaceSize=2G
            -XX:MaxMetaspaceSize=2G
            -XX:ReservedCodeCacheSize=2G
            -XX:MaxRAMPercentage=50
    volumes:
      - "./SAMLv2-config.groovy:/etc/irius/SAMLv2-config.groovy" 
      - "./idp.xml:/etc/irius/idp.xml" 
      - "./iriusrisk-sp.jks:/etc/irius/iriusrisk-sp.jks"

secrets:
  db_pwd:
    external: true
  db_privkey:
    external: true
  keystore_pwd:
    external: true
  keystore_privkey:
    external: true
  key_alias_pwd:
    external: true
  key_alias_privkey:
    external: true