version: '3.7'
networks:
  iriusrisk-frontend:
services:
  postgres:
    image: localhost/postgres-gpg:15.4
    container_name: iriusrisk-postgres
    ports:
      - "5432:5432"
    secrets:
      - db_pwd
      - db_privkey
    environment:
      POSTGRES_USER: postgres
    networks:
      - iriusrisk-frontend
    volumes:
      - "./postgres/data:/var/lib/postgresql/data:z"
    
secrets:
  db_pwd:
    external: true
  db_privkey:
    external: true