version: '3.7'

networks:
  iriusrisk-frontend:
  iriusrisk-backend:

services:

  startleft:
    restart: unless-stopped
    environment:
      - IRIUS_SERVER=http://tomcat:8080
    image: docker.io/continuumsecurity/iriusrisk-prod:startleft
    container_name: iriusrisk-startleft
    command: ["uvicorn", "startleft.startleft.api.fastapi_server:webapp", "--host", "0.0.0.0", "--port", "8081"]
    networks:
      - iriusrisk-backend
    mem_reservation: 1G
    mem_limit: 2G

  reporting-module:
    restart: unless-stopped
    image: docker.io/continuumsecurity/iriusrisk-prod:reporting-module
    container_name: reporting-module
    networks:
      - iriusrisk-backend
    ports:
      - '3000:3000'